### ISSUE TITLE
Future plans for annotation pipeline project

### ISSUE THREAD

**Issue by omerb01** [metaspace2020/pywren-annotation-pipeline#31] opened 2019-06-27 08:04 UTC
few things I thought about for the next generations of annotation pipeline project.
1. currently we segment centroids chunks database by this logic: clip every centroids chunk according to the dataset and at last we merge all clipped chunks together and segment it into the desired number of segments. I think it will be better if we can segment each clipped chunk separately and then merge segments if needed cause currently its memory depends on the dataset/database (with "huge" input, it can get up to 4GB) we need to check if such logic is possible.
2. currently we split the dataset locally into chunks and then upload each chunk into COS one by one. it will be better if we could split it inside COS to reduce times.
3. lets assume we have N dataset segments. currently we segment each dataset chunk into N segments and save every chunk segments into COS and then we merge all chunks segments together and store it again as a dataset segment. so we firstly store `N * number_of_chunks` into COS. in the huge dataset for example, we have ~700 dataset segments and 11 dataset chunks so 7700 objs will be stored in that case. we need to minimise the number of different segments in each dataset chunk to reduce the number of connections to COS.

**Comment by LachlanStuart** [comment] 2019-06-27 16:01
@omerb01 

> 1. currently we segment centroids chunks database by this logic: ...

I've forgotten the specifics about this part of the pipeline - @intsco do you have any thoughts?

> 2. currently we split the dataset locally into chunks and then upload each chunk into COS one by one. it will be better if we could split it inside COS to reduce times.

In a WIP PR I moved the uploading part into a separate thread, so that it doesn't have to wait for the upload to finish before starting to split the next chunk:

https://github.com/metaspace2020/pywren-annotation-pipeline/commit/4e125f4ef14fb75fba3e55fe4f2d96654b74ad5b?w=1#diff-cd2797b225376cac3bb128a96807ec8e

The improvement depends completely on connection speed, but for me it reduced the time spent on this step for the "big" dataset from 66s to 32s

> 3. we need to minimise the number of different segments in each dataset chunk to reduce the number of connections to COS.

Are the number of COS connections a bottleneck? This `number_of_input_segments * number_of_output_segments` pattern happens in several places because we need to repartition the data, but the outputs need to be chunked because the inputs are too big to load all at once.

Possibly something isn't being sorted correctly, because I thought that each centroids segment only cared about a small number of dataset chunks. I would expect that at least half of those 7700 objs to be empty, but when I download them and look inside they all have data. We could potentially reorganize the data so that many output chunks are empty, and then just not write the empty chunks to COS, but it would be a lot of effort and I'm not sure how much it would help...

**Comment by intsco** [comment] 2019-06-28 09:08
>>1. currently we segment centroids chunks database by this logic: ...

>I've forgotten the specifics about this part of the pipeline - @intsco do you have any thoughts?

@LachlanStuart  sorry but `pywren-annotation-pipeline` database (centroids) segmentation diverged significantly from the original metaspace engine version so I can't add much here.

**Comment by omerb01** [comment] 2019-08-01 08:04
@LachlanStuart regarding the 3rd part - I do think that this is something we need to keep in mind when we use COS. I ran the "huge" dataset 10 times in a row and got an unexpected exception which told me that the maximum number of COS requests (in a timestamp) has been reached.
I think your suggestion is exactly what I mean - the ideal thing here is to prepare chunks at the stage of `split_ds()` func  with minimum number of segments involved for each chunk.
do you think its possible to be implemented?

@intsco regarding the database memory usage - the main issue here is that we need to sort all centroids at the stage of `segment_centr_df()` func, my question is if is there a way we can predict mz bounds as much like we do for the dataset?

**Comment by intsco** [comment] 2019-08-05 12:02
@omerb01 if I understand correctly the code of `segment_centr_df` function, the problem is not specifically in sorting but in all the steps needed for segmenting being done in one function.
We do predict (calculate) bounds for the centroids the same way as for the dataset: given the desired number of segments N, we split centroids (using `np.quantile`) evenly so that each segment has approximately the same number of elements.

**Comment by LachlanStuart** [comment] 2019-08-05 16:00
@omerb01 Sorry, I confused centroid segments and dataset segments when I said that. 

The chunks uploaded by `split_ds()` aren't sorted because that's the order we get the data from the input file. `split_ds()` just tries to upload the data as efficiently as possible so that `segment_centroids` can do the actual sorting.

I can't think of anything that can be done in `split_ds()` except for tuning `chunk_size` so that the chunks are as big as possible without causing `segment_spectra()` to run out of memory. Unfortunately dataset spectra sizes can differ significantly. The current value of `chunk_size` has been set to a value that should work well even in datasets with big spectra, but it would probably be better to have chunks that contain a variable number of spectra and try to hit a size target.

**Comment by omerb01** [comment] 2019-08-07 11:16
@LachlanStuart I think we are talking about different issues. inside the pipeline we have a step when we split the dataset locally into chunks and upload all chunks into COS - this step is done by `split_ds()`. another step is when we **segment each chunk** into N sub-segments (N is the number of all segments in the end) and then **merge all sub-segments** together into the desire segments - this is done by `segment_spectra()`.
so my question is if there is any way we can reduce the number of sub-segments created. this means to split the dataset locally into chunks with fewer different segments involved instead of all of them.

for example, possible case:
lets assume we have a dataset that we want to segment into 500 segments.
`split_ds()` - splits it into 10 chunks
`segment_spectra()` - **segment each chunk into 500 sub-segments** and then we merge 10 sub-segments to create each segment.
I want to reduce the number of sub-segments that is in bold above.

**Comment by LachlanStuart** [comment] 2019-08-07 13:07
@omerb01 Fundamentally `segment_spectra` is just a sorting function. It works on a dataframe with the columns `(sp_idx, mz, int)`. The input dataframe is sorted by `sp_idx` and it outputs the same data sorted by `mz`. The number of output segments matters for the rest of the pipeline, but the number of input chunks and temporary sub-segments doesn't affect the results.

If there is a better strategy for sorting large arrays with PyWren, then that strategy would also be applicable here. The current implementation is the simplest strategy I know of that can fit into one map-reduce pass, but I'm not an expert - there may be better distributed algorithms available. 

There's two ways I can think of to improve it in this specific use case:
1. Do another round of segmentation after merging each group of sub-segments, so that the number of sub-segments per chunk can be lower than the number of output segments. This could improve the situation a lot, but would eventually run into limitations on the number of sub-segment files again.
2. Allow wasteful reads - for each output segment, read all chunks and then throw away unneeded data. This means no sub-segment temp files, but a lot of extra data transferred.

**Closed as completed** 2019-09-22 15:22 UTC
